name: Annotation
on: push
jobs: # jobsキーへ複数のジョブを定義すると並列に実行される
  log:
    runs-on: ubuntu-latest
    steps:
      - run: echo "::error::This is an error"    # Errorレベルのアノテーション
      - run: echo "::warning::This is a warning" # Warningレベルのアノテーション
      - run: echo "::notice::This is a notice"   # Noticeレベルのアノテーション